layout: default
title: Tiny Little Steps
email: myHappniess@therestofyou.com
description: >- # this means to ignore newlines until "baseurl:"
 Where crows arrive at slight of hand.
baseurl: "" # the subpath of your site, e.g., /blog
url: "http://samplebug.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
